SELECT APNT_NO,PT_NAME,P.PT_NO,D.MCDP_CD,DR_NAME,APNT_YMD
FROM  APPOINTMENT a 
JOIN PATIENT p 
    ON p.PT_NO = a.PT_NO
JOIN DOCTOR d 
    ON a.MDDR_ID = d.DR_ID
WHERE d.MCDP_CD = "CS"
    AND APNT_YMD LIKE "%2022-04-13%"
    AND APNT_CNCL_YN = "N"
ORDER BY APNT_YMD